### ISSUE TITLE
files with silent parts fail to work

### ISSUE THREAD

**Issue by pjrobertson** [scaperot/the-BPM-detector-python#1]
Find a wav file with no audio for a part of the song (longer than the 'window' period) and the script fails to correlate.

[Here](https://gist.github.com/pjrobertson/6289687) is a gist of the changes I made (probably not the best solution):

**Comment by scaperot** [comment]
Hey thanks . Haven't taken a look at this in a while but it looks like a pretty straight forward fix thanks for the patch.

**Comment by scaperot** [comment]
Added in...
