### ISSUE TITLE
BPM intervals not equal to total .wav length?

### ISSUE THREAD

**Issue by amcnear** [scaperot/the-BPM-detector-python#2]
I've analyzed a 15 minute long .wav file and set the window for 060 seconds, and I get only 13 distinct 
BPM estimations. Does the script ignore sections of the file that it cannot get a rythym from (ie, in the 15 minute file, only 13 minute's worth were able to be analyzed.) Thanks!

**Comment by scaperot** [comment]
see latest checkout for an off by one error, which doesn't really explain your off by two question.  if you printout the max_windows_ndx, it should say how many windows you will have for a file.  It will not scan anything at the end that is smaller than the window size, so perhaps its just a little less than 15minutes?  When I run this with a file with 263.4s and a window size of 3s, I get 87 windows.  Try the newest version and let me know if you at least get 14 windows.  Good luck!!
