### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by petepm** [scaperot/the-BPM-detector-python#4]
All code should have one, just in case!

**Comment by eladyarom** [comment]
Hi, I was wondering if I could use this code in a project, so I was wondering about the licence as well?

Edit: Actually, I ended up using https://github.com/aubio/aubio/blob/master/python/demos/demo_bpm_extract.py as it ended up being a lot easier, but I agree with petepm :)

**Comment by scaperot** [comment]
Done.
